sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tJjyQt1koA5p6CSvjEV
    access-key-secret: JtTsB7nj1CBziZE4a3vA5fiVkcqRQS
    bucket-name: sky-nnnu
  redis:
    host: localhost
    port: 6379
    database: 10