sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: ???
    access-key-secret: ???
    bucket-name: sky-nnnu
  redis:
    host: localhost
    port: 6379
    database: 10
  wechat:
    appid: ???
    secret: ???
    mchid:
    mch-serial-no:
    private-key-file-path:
    api-v3-key:
    we-chat-pay-cert-file-path:
    notify-url: https://12b3e0a9.r20.cpolar.top/paySuccess
    refund-notify-url: https://12b3e0a9.r20.cpolar.top/refundSuccess
